/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package hu.daq.thriftconnector.thrift;

import org.apache.thrift.scheme.IScheme;
import org.apache.thrift.scheme.SchemeFactory;
import org.apache.thrift.scheme.StandardScheme;

import org.apache.thrift.scheme.TupleScheme;
import org.apache.thrift.protocol.TTupleProtocol;
import org.apache.thrift.protocol.TProtocolException;
import org.apache.thrift.EncodingUtils;
import org.apache.thrift.TException;
import org.apache.thrift.async.AsyncMethodCallback;
import org.apache.thrift.server.AbstractNonblockingServer.*;
import java.util.List;
import java.util.ArrayList;
import java.util.Map;
import java.util.HashMap;
import java.util.EnumMap;
import java.util.Set;
import java.util.HashSet;
import java.util.EnumSet;
import java.util.Collections;
import java.util.BitSet;
import java.nio.ByteBuffer;
import java.util.Arrays;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

public class TimeReport implements org.apache.thrift.TBase<TimeReport, TimeReport._Fields>, java.io.Serializable, Cloneable, Comparable<TimeReport> {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("TimeReport");

  private static final org.apache.thrift.protocol.TField LEGTIME_FIELD_DESC = new org.apache.thrift.protocol.TField("legtime", org.apache.thrift.protocol.TType.STRUCT, (short)1);
  private static final org.apache.thrift.protocol.TField BALLTIME_FIELD_DESC = new org.apache.thrift.protocol.TField("balltime", org.apache.thrift.protocol.TType.STRUCT, (short)2);

  private static final Map<Class<? extends IScheme>, SchemeFactory> schemes = new HashMap<Class<? extends IScheme>, SchemeFactory>();
  static {
    schemes.put(StandardScheme.class, new TimeReportStandardSchemeFactory());
    schemes.put(TupleScheme.class, new TimeReportTupleSchemeFactory());
  }

  public TimeDescriptor legtime; // required
  public TimeDescriptor balltime; // required

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    LEGTIME((short)1, "legtime"),
    BALLTIME((short)2, "balltime");

    private static final Map<String, _Fields> byName = new HashMap<String, _Fields>();

    static {
      for (_Fields field : EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // LEGTIME
          return LEGTIME;
        case 2: // BALLTIME
          return BALLTIME;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    public static _Fields findByName(String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final String _fieldName;

    _Fields(short thriftId, String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  public static final Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.LEGTIME, new org.apache.thrift.meta_data.FieldMetaData("legtime", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.StructMetaData(org.apache.thrift.protocol.TType.STRUCT, TimeDescriptor.class)));
    tmpMap.put(_Fields.BALLTIME, new org.apache.thrift.meta_data.FieldMetaData("balltime", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.StructMetaData(org.apache.thrift.protocol.TType.STRUCT, TimeDescriptor.class)));
    metaDataMap = Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(TimeReport.class, metaDataMap);
  }

  public TimeReport() {
  }

  public TimeReport(
    TimeDescriptor legtime,
    TimeDescriptor balltime)
  {
    this();
    this.legtime = legtime;
    this.balltime = balltime;
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public TimeReport(TimeReport other) {
    if (other.isSetLegtime()) {
      this.legtime = new TimeDescriptor(other.legtime);
    }
    if (other.isSetBalltime()) {
      this.balltime = new TimeDescriptor(other.balltime);
    }
  }

  public TimeReport deepCopy() {
    return new TimeReport(this);
  }

  @Override
  public void clear() {
    this.legtime = null;
    this.balltime = null;
  }

  public TimeDescriptor getLegtime() {
    return this.legtime;
  }

  public TimeReport setLegtime(TimeDescriptor legtime) {
    this.legtime = legtime;
    return this;
  }

  public void unsetLegtime() {
    this.legtime = null;
  }

  /** Returns true if field legtime is set (has been assigned a value) and false otherwise */
  public boolean isSetLegtime() {
    return this.legtime != null;
  }

  public void setLegtimeIsSet(boolean value) {
    if (!value) {
      this.legtime = null;
    }
  }

  public TimeDescriptor getBalltime() {
    return this.balltime;
  }

  public TimeReport setBalltime(TimeDescriptor balltime) {
    this.balltime = balltime;
    return this;
  }

  public void unsetBalltime() {
    this.balltime = null;
  }

  /** Returns true if field balltime is set (has been assigned a value) and false otherwise */
  public boolean isSetBalltime() {
    return this.balltime != null;
  }

  public void setBalltimeIsSet(boolean value) {
    if (!value) {
      this.balltime = null;
    }
  }

  public void setFieldValue(_Fields field, Object value) {
    switch (field) {
    case LEGTIME:
      if (value == null) {
        unsetLegtime();
      } else {
        setLegtime((TimeDescriptor)value);
      }
      break;

    case BALLTIME:
      if (value == null) {
        unsetBalltime();
      } else {
        setBalltime((TimeDescriptor)value);
      }
      break;

    }
  }

  public Object getFieldValue(_Fields field) {
    switch (field) {
    case LEGTIME:
      return getLegtime();

    case BALLTIME:
      return getBalltime();

    }
    throw new IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new IllegalArgumentException();
    }

    switch (field) {
    case LEGTIME:
      return isSetLegtime();
    case BALLTIME:
      return isSetBalltime();
    }
    throw new IllegalStateException();
  }

  @Override
  public boolean equals(Object that) {
    if (that == null)
      return false;
    if (that instanceof TimeReport)
      return this.equals((TimeReport)that);
    return false;
  }

  public boolean equals(TimeReport that) {
    if (that == null)
      return false;

    boolean this_present_legtime = true && this.isSetLegtime();
    boolean that_present_legtime = true && that.isSetLegtime();
    if (this_present_legtime || that_present_legtime) {
      if (!(this_present_legtime && that_present_legtime))
        return false;
      if (!this.legtime.equals(that.legtime))
        return false;
    }

    boolean this_present_balltime = true && this.isSetBalltime();
    boolean that_present_balltime = true && that.isSetBalltime();
    if (this_present_balltime || that_present_balltime) {
      if (!(this_present_balltime && that_present_balltime))
        return false;
      if (!this.balltime.equals(that.balltime))
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    return 0;
  }

  @Override
  public int compareTo(TimeReport other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;

    lastComparison = Boolean.valueOf(isSetLegtime()).compareTo(other.isSetLegtime());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetLegtime()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.legtime, other.legtime);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetBalltime()).compareTo(other.isSetBalltime());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetBalltime()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.balltime, other.balltime);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    schemes.get(iprot.getScheme()).getScheme().read(iprot, this);
  }

  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    schemes.get(oprot.getScheme()).getScheme().write(oprot, this);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder("TimeReport(");
    boolean first = true;

    sb.append("legtime:");
    if (this.legtime == null) {
      sb.append("null");
    } else {
      sb.append(this.legtime);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("balltime:");
    if (this.balltime == null) {
      sb.append("null");
    } else {
      sb.append(this.balltime);
    }
    first = false;
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    // check for sub-struct validity
    if (legtime != null) {
      legtime.validate();
    }
    if (balltime != null) {
      balltime.validate();
    }
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, ClassNotFoundException {
    try {
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class TimeReportStandardSchemeFactory implements SchemeFactory {
    public TimeReportStandardScheme getScheme() {
      return new TimeReportStandardScheme();
    }
  }

  private static class TimeReportStandardScheme extends StandardScheme<TimeReport> {

    public void read(org.apache.thrift.protocol.TProtocol iprot, TimeReport struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // LEGTIME
            if (schemeField.type == org.apache.thrift.protocol.TType.STRUCT) {
              struct.legtime = new TimeDescriptor();
              struct.legtime.read(iprot);
              struct.setLegtimeIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 2: // BALLTIME
            if (schemeField.type == org.apache.thrift.protocol.TType.STRUCT) {
              struct.balltime = new TimeDescriptor();
              struct.balltime.read(iprot);
              struct.setBalltimeIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      struct.validate();
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot, TimeReport struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      if (struct.legtime != null) {
        oprot.writeFieldBegin(LEGTIME_FIELD_DESC);
        struct.legtime.write(oprot);
        oprot.writeFieldEnd();
      }
      if (struct.balltime != null) {
        oprot.writeFieldBegin(BALLTIME_FIELD_DESC);
        struct.balltime.write(oprot);
        oprot.writeFieldEnd();
      }
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class TimeReportTupleSchemeFactory implements SchemeFactory {
    public TimeReportTupleScheme getScheme() {
      return new TimeReportTupleScheme();
    }
  }

  private static class TimeReportTupleScheme extends TupleScheme<TimeReport> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, TimeReport struct) throws org.apache.thrift.TException {
      TTupleProtocol oprot = (TTupleProtocol) prot;
      BitSet optionals = new BitSet();
      if (struct.isSetLegtime()) {
        optionals.set(0);
      }
      if (struct.isSetBalltime()) {
        optionals.set(1);
      }
      oprot.writeBitSet(optionals, 2);
      if (struct.isSetLegtime()) {
        struct.legtime.write(oprot);
      }
      if (struct.isSetBalltime()) {
        struct.balltime.write(oprot);
      }
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, TimeReport struct) throws org.apache.thrift.TException {
      TTupleProtocol iprot = (TTupleProtocol) prot;
      BitSet incoming = iprot.readBitSet(2);
      if (incoming.get(0)) {
        struct.legtime = new TimeDescriptor();
        struct.legtime.read(iprot);
        struct.setLegtimeIsSet(true);
      }
      if (incoming.get(1)) {
        struct.balltime = new TimeDescriptor();
        struct.balltime.read(iprot);
        struct.setBalltimeIsSet(true);
      }
    }
  }

}

